# Generated by Django 5.2.14 on 2026-05-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('local', 'Local path')], default='github', max_length=20)),
                ('local_path', models.CharField(blank=True, max_length=1000)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'url'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('final_answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='research.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.repository')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.researchsession')),
            ],
            options={
                'ordering': ['file_path', 'line_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_preview', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='research.researchsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['repository', '-created_at'], name='research_re_reposit_2856d1_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['status'], name='research_re_status_6c4712_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['repository', 'file_path'], name='research_fi_reposit_97f7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['session', 'file_path'], name='research_fi_session_de981c_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['session', 'created_at'], name='research_to_session_131fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['tool_name'], name='research_to_tool_na_9863cb_idx'),
        ),
    ]
